<?php
// Bulk import 1688 adult wellness products collected 2026-06-19.
// Run from OpenCart upload root: php database/2026-06-19-bulk-1688-wellness-products.php
require 'config.php';
$mysqli = new mysqli(DB_HOSTNAME, DB_USERNAME, DB_PASSWORD, DB_DATABASE, (int)DB_PORT);
if ($mysqli->connect_errno) { fwrite(STDERR, "DB connect failed\n"); exit(1); }
$mysqli->set_charset('utf8mb4');
$prefix = DB_PREFIX; $lang = 1; $store = 0;
function q($s){global $mysqli; return $mysqli->real_escape_string((string)$s);} 
function one($sql){global $mysqli; $r=$mysqli->query($sql); if(!$r) throw new Exception($mysqli->error."\n".$sql); $row=$r->fetch_row(); return $row?$row[0]:null;}
function execq($sql){global $mysqli; if(!$mysqli->query($sql)) throw new Exception($mysqli->error."\n".$sql); return $mysqli->insert_id;}
function ensure_category($name,$parent_id=0){global $prefix,$lang,$store,$mysqli; $id=one("SELECT c.category_id FROM `{$prefix}category` c JOIN `{$prefix}category_description` cd ON c.category_id=cd.category_id WHERE cd.language_id=$lang AND cd.name='".q($name)."' LIMIT 1"); if(!$id){execq("INSERT INTO `{$prefix}category` SET image='', parent_id=".(int)$parent_id.", sort_order=30, status=1"); $id=$mysqli->insert_id; $desc='<p>Private adult wellness products selected for discreet packaging, responsible 18+ shopping, and secure checkout.</p>'; execq("INSERT INTO `{$prefix}category_description` SET category_id=$id, language_id=$lang, name='".q($name)."', description='".q($desc)."', meta_title='".q($name.' | Lovanest Adult Wellness')."', meta_description='".q('Shop '.$name.' with discreet packaging, private billing and secure PayPal checkout. Adults 18+ only.')."', meta_keyword='' "); execq("INSERT IGNORE INTO `{$prefix}category_to_store` SET category_id=$id, store_id=$store"); if($parent_id){$rows=$mysqli->query("SELECT path_id, level FROM `{$prefix}category_path` WHERE category_id=".(int)$parent_id." ORDER BY level"); while($row=$rows->fetch_assoc()) execq("INSERT INTO `{$prefix}category_path` SET category_id=$id, path_id=".(int)$row['path_id'].", level=".(int)$row['level']); $level=(int)one("SELECT MAX(level)+1 FROM `{$prefix}category_path` WHERE category_id=$id");} else {$level=0;} execq("INSERT INTO `{$prefix}category_path` SET category_id=$id, path_id=$id, level=$level");} $kw=strtolower(preg_replace('/[^a-z0-9]+/','-',trim($name))); $kw=trim($kw,'-'); $seo=one("SELECT seo_url_id FROM `{$prefix}seo_url` WHERE `key`='path' AND value='".q($id)."' AND language_id=$lang AND store_id=$store LIMIT 1"); if(!$seo) execq("INSERT INTO `{$prefix}seo_url` SET store_id=$store, language_id=$lang, `key`='path', value='".q($id)."', keyword='".q($kw)."', sort_order=0"); return (int)$id;}
function ensure_attr($name){global $prefix,$lang,$mysqli; $group=one("SELECT attribute_group_id FROM `{$prefix}attribute_group_description` WHERE language_id=$lang AND name='Wellness Details' LIMIT 1"); if(!$group){execq("INSERT INTO `{$prefix}attribute_group` SET sort_order=1"); $group=$mysqli->insert_id; execq("INSERT INTO `{$prefix}attribute_group_description` SET attribute_group_id=$group, language_id=$lang, name='Wellness Details'");} $id=one("SELECT a.attribute_id FROM `{$prefix}attribute` a JOIN `{$prefix}attribute_description` ad ON a.attribute_id=ad.attribute_id WHERE ad.language_id=$lang AND ad.name='".q($name)."' LIMIT 1"); if(!$id){execq("INSERT INTO `{$prefix}attribute` SET attribute_group_id=$group, sort_order=1"); $id=$mysqli->insert_id; execq("INSERT INTO `{$prefix}attribute_description` SET attribute_id=$id, language_id=$lang, name='".q($name)."'");} return (int)$id;}
$root=ensure_category('Adult Wellness',0);
$products = json_decode(file_get_contents(__DIR__ . '/2026-06-19-bulk-1688-wellness-products.json'), true);
foreach($products as $p){
  $cat=ensure_category($p['category'],$root);
  $slug=$p['slug']; $model=$p['model']; $name=$p['name'];
  $main="catalog/adult-wellness/$slug/$slug-01.jpg";
  $desc="<section class=\"product-wellness-copy\"><h2>".q($name)."</h2><p>A private adult wellness product selected for responsible 18+ shoppers, clean presentation, discreet delivery, and secure checkout.</p><h3>Key Benefits</h3><ul><li>Designed for private adult wellness and discreet storage.</li><li>Clear English specifications and variant guidance.</li><li>Selected for plain packaging and privacy-first shopping.</li><li>Ships with no adult product names on the outside.</li></ul><h3>Specifications</h3><ul><li><strong>Material:</strong> ".q($p['material'])."</li><li><strong>Model:</strong> ".q($model)."</li><li><strong>Noise Level:</strong> ".q($p['noise'])."</li><li><strong>Weight:</strong> ".q($p['weight'])."</li><li><strong>Available Variants:</strong> ".q($p['variants'])."</li><li><strong>Recommended Age:</strong> Adults 18+ only</li></ul><h3>Care & Privacy</h3><p>Clean before and after use according to the included care instructions. Store dry and away from heat. This product is prepared for discreet shipping.</p></section>";
  $pid=one("SELECT product_id FROM `{$GLOBALS['prefix']}product` WHERE model='".q($model)."' LIMIT 1");
  if(!$pid){execq("INSERT INTO `{$GLOBALS['prefix']}product` SET master_id=0, model='".q($model)."', location='', variant='', override='', quantity=500, stock_status_id=7, image='".q($main)."', manufacturer_id=0, shipping=1, price=".q($p['price']).", points=0, tax_class_id=0, date_available=CURDATE(), weight='0.30000000', weight_class_id=2, length='0', width='0', height='0', length_class_id=1, subtract=0, minimum=1, sort_order=20, status=1"); $pid=$mysqli->insert_id;} else {execq("UPDATE `{$GLOBALS['prefix']}product` SET image='".q($main)."', price=".q($p['price']).", quantity=500, status=1 WHERE product_id=".(int)$pid); $mysqli->query("DELETE FROM `{$GLOBALS['prefix']}product_description` WHERE product_id=".(int)$pid." AND language_id=$lang"); $mysqli->query("DELETE FROM `{$GLOBALS['prefix']}product_to_category` WHERE product_id=".(int)$pid); $mysqli->query("DELETE FROM `{$GLOBALS['prefix']}product_to_store` WHERE product_id=".(int)$pid); $mysqli->query("DELETE FROM `{$GLOBALS['prefix']}product_image` WHERE product_id=".(int)$pid);}
  execq("INSERT INTO `{$GLOBALS['prefix']}product_description` SET product_id=$pid, language_id=$lang, name='".q($name)."', description='".q($desc)."', tag='adult wellness, discreet shipping, private wellness', meta_title='".q($name.' | Lovanest')."', meta_description='".q('Shop '.$name.' with English specs, discreet packaging and secure PayPal checkout. Adults 18+ only.')."', meta_keyword='' ");
  execq("INSERT IGNORE INTO `{$GLOBALS['prefix']}product_to_store` SET product_id=$pid, store_id=$store"); execq("INSERT IGNORE INTO `{$GLOBALS['prefix']}product_to_category` SET product_id=$pid, category_id=$cat");
  for($i=2;$i<=$p['image_count'];$i++){ $n=str_pad((string)$i,2,'0',STR_PAD_LEFT); execq("INSERT INTO `{$GLOBALS['prefix']}product_image` SET product_id=$pid, image='catalog/adult-wellness/$slug/$slug-$n.jpg', sort_order=".($i-1)); }
  $attrs=['Material'=>$p['material'],'Size & Fit'=>$p['size'],'Power / Charging'=>$p['power'],'Noise Level'=>$p['noise'],'Package Includes'=>$p['package'],'Best For'=>$p['best'],'Cleaning'=>'Clean before and after use; store dry; follow included care instructions.','Discreet Shipping'=>'Ships in plain packaging with no adult product names outside.','Available Variants'=>$p['variants'],'Source Reference'=>$p['source']];
  $mysqli->query("DELETE FROM `{$GLOBALS['prefix']}product_attribute` WHERE product_id=$pid"); foreach($attrs as $an=>$av){$aid=ensure_attr($an); execq("INSERT INTO `{$GLOBALS['prefix']}product_attribute` SET product_id=$pid, attribute_id=$aid, language_id=$lang, text='".q($av)."'");}
  $seo=one("SELECT seo_url_id FROM `{$GLOBALS['prefix']}seo_url` WHERE `key`='product_id' AND value='".q($pid)."' AND language_id=$lang AND store_id=$store LIMIT 1"); if(!$seo) execq("INSERT INTO `{$GLOBALS['prefix']}seo_url` SET store_id=$store, language_id=$lang, `key`='product_id', value='".q($pid)."', keyword='".q($slug)."', sort_order=0"); else execq("UPDATE `{$GLOBALS['prefix']}seo_url` SET keyword='".q($slug)."' WHERE seo_url_id=$seo");
  echo $p['id']." product_id=$pid category=$cat images=".$p['image_count']."\n";
}
